### ISSUE TITLE
Caching doesn't work (for me)

### ISSUE THREAD

**Issue by jeroenvandijk** [DeLaGuardo/setup-graalvm#1]
Hi Kirill,

Thank you for sharing this Github Action!

It works perfectly expect for caching of the GraalVM download. It seems to add 30 unnecessary seconds for each build.

This is my configuration:
```
      - name: Prepare GraalVM
        uses: DeLaGuardo/setup-graalvm@2.0
        with:
          graalvm-version: "19.3.0.java8"

      - name: Install native-image
        run: |
          echo 
          gu install native-image
```

The `Prepare GraalVM` step takes around 30 seconds. Did I miss something in my configuration?

It seems your code tries to detect this situation here https://github.com/DeLaGuardo/setup-graalvm/blob/master/src/installer.ts#L43

**Comment by DeLaGuardo** [comment]
Thanks for spotting that out. Will try to resolve asap

**Comment by DeLaGuardo** [comment]
Could you change your workflow file?

```yaml
      - name: Prepare GraalVM
        uses: DeLaGuardo/setup-graalvm@2.0
        with:
          graalvm-version: "19.3.0.java8"

      - name: Second prepare GraalVM
        uses: DeLaGuardo/setup-graalvm@2.0
        with:
          graalvm-version: "19.3.0.java8"

      - name: Install native-image
        run: |
          echo 
          gu install native-image
```

`tool-cache` suppose to keep the cache until you have something to run and got wiped after finish

![image](https://user-images.githubusercontent.com/542042/74759562-41ff6b00-5279-11ea-860b-ab6b892170cc.png)

**Comment by jeroenvandijk** [comment]
I'm still waiting for the new job to complete

Also I didn't mention it, but this is a run on a mac (`runs-on: macOS-latest`). I'll add a run for Linux to see if it works there

**Comment by jeroenvandijk** [comment]
Ok the step `Second prepare GraalVM` in the Mac Osx takes 0 seconds. When I test this on a Linux machine I see the same behaviour.

I've been able to cache other steps (maven dependencies), but for this I had to add:
```
      - name: Cache deps
        uses: actions/cache@v1
        id: cache-deps
        with: 
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('project.clj') }} # Other deps files?
          restore-keys: |
                ${{ runner.os }}-maven-
  
      - name: Fetch deps
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          lein deps
```
I couldn't find anything like that in your code (could have look wrong of course)
