### ISSUE TITLE
4.0/21.0.0.2 not working for me :-(

### ISSUE THREAD

**Issue by zemiak** [DeLaGuardo/setup-graalvm#17]
Hello,

this is probably a totally newbie question, but the native build in actions is not working form me. It looks, like the graalvm is not downloaded at all and the gu is failing (command not found)

action:
```
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install graalvm
      id: setup-graalvm
      uses: DeLaGuardo/setup-graalvm@4.0
      with:
        # GraalVM version, no pattern syntax available atm
        graalvm-version: '21.0.0.2'
        # optional, available: java8 and java11, defaults to java8
        java: java11
        # optional, available: amd64 and aarch64, defaults to amd64
        arch: amd64
    - name: env
      run: |
        set
    - name: List RUNNER_TEMP
      run: |
        ls -lR ${RUNNER_TEMP}
    - name: Install native-image component
      run: |
        gu install native-image
    # - name: Set version
    #   run: ./mvnw versions:set -DnewVersion="${{ github.event.release.tag_name }}"
    - name: Build native executable
      run: ./mvnw package -Dnative
```

outputs:

Install Graalvm
```
Run DeLaGuardo/setup-graalvm@4.0
  with:
    graalvm-version: 21.0.0.2
    java: java11
    arch: amd64
    graalvm: 21.0.0.2
```

env:
```
...
RUNNER_OS=macOS
RUNNER_PERFLOG=/usr/local/opt/runner/perflog
RUNNER_TEMP=/Users/runner/work/_temp
RUNNER_TOOL_CACHE=/Users/runner/hostedtoolcache
...
```

List RUNNER_TEMP (no Graal here!)
```
Run ls -lR ${RUNNER_TEMP}
total 16
-rw-r--r--   1 runner  staff   22 Jul  8 17:03 493141f9-c937-4065-98f8-151e80d65bdc.sh
-rw-r--r--   1 runner  staff    4 Jul  8 17:03 9525d355-0ac2-452b-b0a4-6a7b517770d5.sh
drwxr-xr-x   3 runner  staff   96 Jul  8 17:03 _github_workflow
drwxr-xr-x  10 runner  staff  320 Jul  8 17:03 _runner_file_commands

/Users/runner/work/_temp/_github_workflow:
total 16
-rw-r--r--  1 runner  staff  8033 Jul  8 17:03 event.json

/Users/runner/work/_temp/_runner_file_commands:
total 0
-rw-r--r--  1 runner  staff  0 Jul  8 17:03 add_path_1a98b41f-d9cf-434d-88d6-9722aba925e3
-rw-r--r--  1 runner  staff  0 Jul  8 17:03 add_path_3a66a390-fa88-4380-b96c-e9b6e537afcd
-rw-r--r--  1 runner  staff  0 Jul  8 17:03 add_path_6136500f-93fb-4b5b-94f6-fcee9e78f68d
-rw-r--r--  1 runner  staff  0 Jul  8 17:03 add_path_eebeabd2-9fde-4cb3-b726-18933fe25764
-rw-r--r--  1 runner  staff  0 Jul  8 17:03 set_env_1a98b41f-d9cf-434d-88d6-9722aba925e3
-rw-r--r--  1 runner  staff  0 Jul  8 17:03 set_env_3a66a390-fa88-4380-b96c-e9b6e537afcd
-rw-r--r--  1 runner  staff  0 Jul  8 17:03 set_env_6136500f-93fb-4b5b-94f6-fcee9e78f68d
-rw-r--r--  1 runner  staff  0 Jul  8 17:03 set_env_eebeabd2-9fde-4cb3-b726-18933fe25764
```

Install native-image component (fails because gu is not here)
```
Run gu install native-image
/Users/runner/work/_temp/38be676a-2ae1-4a2d-8a23-409c40d818f1.sh: line 1: gu: command not found
Error: Process completed with exit code 127.
```

With @3 it worked, but I need a newer version of Graal

Thank you and sorry, if I messed up something obvious

Miroslav

**Comment by DeLaGuardo** [comment]
Unfortunately, I can't reproduce it - https://github.com/DeLaGuardo/setup-graalvm/runs/3028104632?check_suite_focus=true

Could you share the complete workflow file? If you don't want to use public channels to share it we can use keybase.io or feel free to send me an email (delaguardo@hey.com)

**Comment by zemiak** [comment]
Thank you for your effort!

Yep, it was me, of course. The problem is the YAML Syntax Hell (most probably):

```
    steps:
    - uses: actions/checkout@v2
    - name: Install graalvm
      id: setup-graalvm
      uses: DeLaGuardo/setup-graalvm@4.0
      with:
        # GraalVM version, no pattern syntax available atm
        graalvm-version: '21.0.0.2'
        # optional, available: java8 and java11, defaults to java8
        java: java11
        # optional, available: amd64 and aarch64, defaults to amd64
        arch: amd64
```

I have taken your simple workflow and adapted it instead of fixing my own and it works now. Sorry for making a fuss, closing now.
