### ISSUE TITLE
Add a flag for installing the native-image tool

### ISSUE THREAD

**Issue by helpermethod** [DeLaGuardo/setup-graalvm#23]
Hi!

First of all, great tool, it's basically my go-to action for setting up GraalVM!

I was wondering if instead of installing the `native-image` executable in a separate `run` step, your action couldn't provide an additional flag for installing the executable, something like `native-image: true`?

This would allow using this action in composite actions, like [here](https://github.com/helpermethod/graalvm-native-image-toolchain/blob/main/action.yml) and generally simplify its usage. Wdyt?

**Comment by DeLaGuardo** [comment]
Hello! Thanks for using it :)

And thanks for a good idea. I can see how it can improve user experience. But at the same native-image is not the only available component. What if instead of "native-image" option there will be an option like "components" taking a list of desired component names?

```yml
    steps:
      - name: Setup GraalVM
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm: '21.3.0'
          java: java17
          components:
            - native-image
            - R
            - python
          personal-token: ${{ secrets.GITHUB_TOKEN }}
```
