### ISSUE TITLE
How to install native image on Windows

### ISSUE THREAD

**Issue by lispyclouds** [DeLaGuardo/setup-graalvm#8]
Thanks a lot for this handy action! 😄 

I have been happily using this for Mac and Linux but wanted to try out native images for Windows too but im running into the following issues when trying to run `gu install native-image`:
- If the default shell(Powershell I think?) is used:
  ```
  Run gu install native-image
    gu install native-image
    shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
    env:
      JAVA_HOME: C:\hostedtoolcache\windows\GraalVM\20.3.0-java11\x64
      JAVA_HOME_20.3.0.java11: C:\hostedtoolcache\windows\GraalVM\20.3.0-java11\x64
      LEIN_HOME: C:\hostedtoolcache\windows\Leiningen\2.9.5\x64
  Get-Unique: D:\a\_temp\1a3e4b20-ff2e-4c1f-8c67-4f71f6a61b6e.ps1:2
  Line |
     2 |  gu install native-image
       |  ~~~~~~~~~~~~~~~~~~~~~~~
       | A positional parameter cannot be found that accepts argument 'install'.

  Error: Process completed with exit code 1.
  ```
- If I use `shell: bash`
  ```
  Run gu install native-image
    gu install native-image
    shell: C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
    env:
      JAVA_HOME: C:\hostedtoolcache\windows\GraalVM\20.3.0-java11\x64
      JAVA_HOME_20.3.0.java11: C:\hostedtoolcache\windows\GraalVM\20.3.0-java11\x64
      LEIN_HOME: C:\hostedtoolcache\windows\Leiningen\2.9.5\x64
  D:\a\_temp\9fd80673-7852-483b-9f69-b700b89aafdc.sh: line 1: gu: command not found
  Error: Process completed with exit code 127.
  ```

This is my YAML
```yaml
- name: Setup GraalVM
  uses: DeLaGuardo/setup-graalvm@master
  with:
    graalvm-version: '20.3.0.java11'
- name: Setup Leiningen
  uses: DeLaGuardo/setup-clojure@master
    with:
      lein: 2.9.5
- name: Install native image toolchain
  shell: bash # Or without this
  run: gu install native-image # This is what fails
```
